### PR TITLE
refactor: improve data generator file for database population

### PR DESCRIPTION
**Pull request by musabsamani**
- Refactored the data generator file for better readability and maintainability
- Optimized functions and logic for generating mock data
- Updated dependencies to the latest versions

### CODE REVIEW

**Comment by musabsamani** [comment]
@AhmedYassinH 

---

The file `/public/data.json` is now ready to be used for populating the database. However, the following 6 properties need updates:

### User
- **Add property**: `birthday` [string date]

### Book
- **Add property**: `ISBN` [string]

### Borrowing
- **Refactor properties**: 
  - Change `authors` to `author` [string]
  - Change `publishers` to `publisher` [string]
- **Add property**: `rejectionReason` [string]

### Book Genre
- **Update genre**: Change `SelfHelp` to `Self-Help`

### userMinimalDTO
- **Change**: Replace with full user object to include `imageURL` in borrowing and user navigation (used in `userNavigation`, `rejectedByNavigation`, `approvedByNavigation`, etc.)

### Additional Notes:
- **User**: The generated user password is hashed.
- **TimeStamp**: The value format is `[8 char string]#+#[updatedAt date]`. The `updatedAt` date is used to indicate when the record was last updated.
- **User ImageURL**: The `imageURL` property consists of two parts: a string indicating gender (`male` or `female`) and a number from 0 to 8. Example values are `male0.jpg` or `female5.jpg`. There are 16 profile images in `/assets/images/profile`, 8 for each gender.
- **Book ISBN**: The `ISBN` property is used by an API to get the book cover based on the book's ISBN number. (Next step: generate random real ISBN values)





### Possible Errors
<div style="background-color: #f9d6d5; padding: 10px; border-radius: 5px;">
    :warning: <strong>Potential Issues After Updating the Properties:</strong>
    <ul>
        <li><strong>userMinimalDTO</strong>: Ensure that the transition from <code>userMinimalDTO</code> to the full user object does not cause any data inconsistencies or break existing functionality.</li>
        <li><strong>TimeStamp</strong>: Ensure the correct format <code>[8 char string]#+#[updatedAt date]</code> is used, as incorrect formats may lead to errors in data processing.</li>
    </ul>
</div>

**Comment by musabsamani** [comment]
@AhmedYassinH  for your review and comments

**Comment by Mr-Som3a** [comment]
keep up

**Review by Mr-Som3a — COMMENTED** [review]
good work, I will ask you about some feature you added

**Pull request merged**
