### PR TITLE
feat: implement statistics and metrics feature in Dashboard component

### PR DESCRIPTION
**Pull request by musabsamani**
Implement statistics and metrics feature to track library activity, including user registrations, book borrowings, and other relevant metrics. This feature provides insights into borrowing trends, top borrowed books, user activity, and more, enhancing the library management system by enabling administrators to make data-driven decisions and optimize user experiences.

          Components added to the Statistics component (part of the Dashboard component):

          1. BarChart: Display borrowing requests by gender (males vs females) for the last 6 months.
          2. BarChart: Display top book category borrowing (males vs females).
          3. BarChart: Display new users registered monthly for the last 12 months.
          4. LineChart: Display borrowing request insights by the most active hours (24-Hour Borrowing Request Insights).
          5. DoughnutChart: Display top borrowed book categories.
          6. DoughnutChart: Display registered users by age.
          7. Map: Display top UAE provinces by borrowing requests.
          8. LineChart: Display reasons for borrowing rejections.
          9. List: Display library operation insights.
          10. List: Display recent activity.
          11. Table: Display top active users.
          12. Table: Display actions to take.

          This comprehensive update enhances the dashboard by providing a visual and analytical overview of the library's operational metrics and user activities.

          **Data Generation**:
          - Used  library for data generation.
          - You can edit the data to be generated by modifying .
          - Running this file will generate a  file in the  folder, which will be used by the app to fetch the data and make it available via the context.
       
@AhmedYassinH 
@Mr-Som3a 
          **Next step**:
          - populate the database with this generated data.

### CODE REVIEW

**Comment by musabsamani** [comment]
@AhmedYassinH 
@Mr-Som3a 
review it and merge it

**Comment by AhmedYassinH** [comment]
Nice
The dashboard looks pretty awesome now 🔥🔥

**Review by AhmedYassinH — APPROVED** [review]

**Comment by Mr-Som3a** [comment]
legend legend 🔥 🔥 🔥

**Review by Mr-Som3a — COMMENTED** [review]
really good job, keep it high bro

**Pull request merged**
