### PR TITLE
feat:reDesign inbox component

### PR DESCRIPTION
**Pull request by Mr-Som3a**

### CODE REVIEW

**Comment by Mr-Som3a** [comment]
@musabsamani  look at common Table component there are some conflict with main , I do some changes for inbox page, and with that changes may affect on others component that  share the same common Table Comp

**Comment by Mr-Som3a** [comment]
I resolved all conflicts and  I will merge them after 10pm , so you can check this commit until that time ! 😁

**Comment by musabsamani** [comment]
Good job, @Mr-Som3a . I'll review the changes and ensure everything aligns well with the main branch. 
It's crucial that the modifications for the inbox page integrate seamlessly without affecting other components. 

I appreciate your proactive approach in resolving the conflicts. Let's touch base after the merge to discuss any further adjustments or enhancements needed. Keep up the great work!

**Review by musabsamani — APPROVED** [review]

**Comment by musabsamani** [comment]
@Mr-Som3a Well Done Mohammed!!

**Pull request merged**
